spring:
  quartz:
    #相关属性配置
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:schema/quartz.sql

## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: it&1997
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true


## Mybatis 配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8082
